"""
File: sdkp/types.py
Framework: FatherTimeSDKP (Size, Density, Kinetic Principle)
Author: Donald Paul Smith | DOI: 10.5281/zenodo.15745609
Description: Centralized type definitions and dataclasses.
             Ensures strict typing, data consistency, and architectural integrity 
             across the Kapnack Solver, VFE1, QCC0, and the Validation engine.
"""

from dataclasses import dataclass
from typing import Optional

@dataclass(frozen=True)
class FrameworkMetadata:
    """
    Immutable metadata lock securing the framework's intellectual property,
    authorship, and versioning across all generated reports.
    """
    framework_name: str
    author: str
    orcid: str
    doi: str
    framework_version: str
    paper_version: str

@dataclass(frozen=True)
class SDVRInputs:
    """
    Standardized Size, Density, Velocity, Rotation (SDVR) input packet.
    Used to pass parameters cleanly into VFE1 and QCC0 modules.
    """
    system_signal: float
    velocity_vector: float
    rotation_rate: float
    local_gravity_modifier: Optional[float] = 1.0

@dataclass
class FieldState:
    """
    Holds the independent execution results from the isolated 
    Vibrational Field Equations (VFE1) and Quantum Correlation Coefficient (QCC0).
    """
    vibrational_resonance: float  # Output from vfe.py
    quantum_correlation: float    # Output from qcc.py

@dataclass
class KapnackResult:
    """
    The exact packing density and security state generated by 
    the Discrete Gradient Processor (Kapnack Engine).
    """
    engine_status: str
    processor_type: str
    exact_packing_density: float
    scaled_density_eos: float
    security_protocol: str
    vault_access: str

@dataclass
class AmiyahEquilibriumState:
    """
    Mathematical assessment of Amiyah's Law of Equilibrium convergence.
    |ρ - ρ_0| < ε
    """
    is_stable: bool
    deviation: float
    convergence_threshold: float

@dataclass
class ValidationReport:
    """
    The immutable audit and validation report generated at the end 
    of every simulation cycle. Hard-coded with the author's IP metadata.
    """
    # Immutable IP & Versioning Block
    metadata: FrameworkMetadata
    validation_timestamp: str
    
    # Validation Metrics
    is_valid: bool
    current_run_accuracy: float
    historical_benchmark: float
    historical_hit_rate: str
    matches_historical: bool
    
    # Equilibrium State
    equilibrium_status: str
    target_deviation: float 
    
    # EOS / c Consistency Tracking
    eos_consistency: float
    c_consistency: float
    reference_ratio: float
    
    # Audit & Security
    vault_status: str
    security_clearance: str
    confidence_score: float
    validation_source: str
    validation_method: str
    audit_note: str
